### ISSUE TITLE
Can you provide a download link of MP6D?

### ISSUE THREAD

**Issue by lhiceu** [junzastar/DFTr_Voting#2]
The MP6D dataset link is unavailable for several months. I would appreciate it if you could provide a new download link.

**Comment by junzastar** [comment]
Hi, sorry for the late reply.
Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).

**Comment by lhiceu** [comment]
> Hi, sorry for the late reply. Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).

Thanks for sharing :)

**Comment by hope57** [comment]
> > Hi, sorry for the late reply. Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).
> 
> Thanks for sharing :)
Excuse me, did you save any other network disks? I downloaded them too slowly

**Comment by hope57** [comment]
> > Hi, sorry for the late reply. Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).
> 
> Thanks for sharing :)
Excuse me, did you save any other network disks? I downloaded them too slowly

**Comment by lhiceu** [comment]
> > > Hi, sorry for the late reply. Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).
> > 
> > 
> > Thanks for sharing :)
> > Excuse me, did you save any other network disks? I downloaded them too slowly

The author of MP6D provided the Baidu Netdisk in readme, you can try it in https://github.com/yhan9848/MP6D

**Comment by hope57** [comment]
> > > > Hi, sorry for the late reply. Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).
> > > 
> > > 
> > > Thanks for sharing :)
> > > Excuse me, did you save any other network disks? I downloaded them too slowly
> 
> The author of MP6D provided the Baidu Netdisk in readme, you can try it in https://github.com/yhan9848/MP6D

Thank you, I found it.  Have you used the MP6D dataset for FFB6D training? The Linemod and Ycb formats I used before are different from this. I don't know how to modify it for training.

**Comment by lhiceu** [comment]
> > > > > Hi, sorry for the late reply. Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).
> > > > 
> > > > 
> > > > Thanks for sharing :)
> > > > Excuse me, did you save any other network disks? I downloaded them too slowly
> > 
> > 
> > The author of MP6D provided the Baidu Netdisk in readme, you can try it in https://github.com/yhan9848/MP6D
> 
> Thank you, I found it. Have you used the MP6D dataset for FFB6D training? The Linemod and Ycb formats I used before are different from this. I don't know how to modify it for training.

I think MP6D is similar to YCB. You can refer to YCB to modify dataloader and config.

**Comment by hope57** [comment]
> > > > > > Hi, sorry for the late reply. Thanks for your interest in our work. I have added the download link of MP6D. You can download it from [here](https://polyuit-my.sharepoint.com/:f:/g/personal/juzhou_polyu_edu_hk/Eim0VkGwNmBJtaI6UWUzMHMBHqCvvwdFj5MVr6Q1Nut32A?e=abisY4).
> > > > > 
> > > > > 
> > > > > Thanks for sharing :)
> > > > > Excuse me, did you save any other network disks? I downloaded them too slowly
> > > 
> > > 
> > > The author of MP6D provided the Baidu Netdisk in readme, you can try it in https://github.com/yhan9848/MP6D
> > 
> > 
> > Thank you, I found it. Have you used the MP6D dataset for FFB6D training? The Linemod and Ycb formats I used before are different from this. I don't know how to modify it for training.
> 
> I think MP6D is similar to YCB. You can refer to YCB to modify dataloader and config.
Thank you. I have already resolved this issue。
